---
# Playbook for installing packages on VMs
- name: "Install Packages"
  hosts: MyChameleonVMs      # specified in the MyInventory file
  collections:
    - openstack.cloud
  remote_user:  cc           # note that the user is ubuntu for 
                             # vagrant-created VM else use the
                             # appropriate user name

  gather_facts: yes          # We ask Ansible to collect all facts
  become_user: yes            # No need for sudo as we are not installing anything

  tasks:
    - name: Install a list of packages
      apt:
        pkg:
        - default-jdk
        - kafka-python
        - python3-pip
        - pip3
        - couchdb-python

    - name: Download kafka
      get_url:
        url: https://archive.apache.org/dist/kafka/2.8.0/kafka_2.12-2.8.0.tgz
        dest: /etc/foo.conf

    - name: Unzip kafka
      command: tar -xzf kafka_2.12-2.8.0.tgz

    - name: replace server properties file
      command: cd kafka_2.12-2.8.0/config/ && rm server.properties

    - name: Copy file
      copy:
        src: ./server.properties  # here you can give absolute path also.
        dest: /home/cc/kafka_2.12-2.8.0/config/    # destination directory into which this file will get copied.

    - name: ufw
      command: ufw limit 9092 && ufw limit 9092/tcp && ufw limit 2181 && ufw limit 2181/tcp
...